### PR TITLE
Added a Chastity Piercing Patch and reduce texture size

### PR DESCRIPTION
**Pull request by Ethryan**
2h cp

And sent the Security Overhaul Patch Textures through Cathedral to reduce the file size on the lock textures.
They are so small so you can't see the difference.

From over 5 mb per texture down to 256 kb.

Downsized to 512x512 textures.

Patched mod is from here: https://www.loverslab.com/topic/141862-devious-chastity-piercing/page/2/#comment-4051770

Fomod is tested and it installs correctly.

### CODE REVIEW

**Comment by IHateMyKite** [comment]
Nice work. Only thing I found is that the patch is missing its patch script. Also, it is intended that only one piercing is patched instead of all 3 ?

**Comment by Ethryan** [comment]
The other 2 items I consider piercings and not something that can be pick-locked away. But I’m going to check them out and see if I can’t come up with something.

Regarding the patch script I couldn’t find any guide on how to create it and I didn’t want to fiddle around with something without knowing how it works.

**Comment by Ethryan** [comment]
Btw, any way to edit the number of locks on a device?

I can't find how to do it.

**Comment by IHateMyKite** [comment]
The number of locks correspond to the size of lock array.
pic
So in this example, device will have 3 locks.

The value in UD_LockList is generated by this tool https://ihatemykite.github.io/LockBitcoder.html

It is important that the UD_LockNameList is correctly set. It needs to have same size.

**Comment by Ethryan** [comment]
Ah, thanks for the explanation.

**Comment by Ethryan** [comment]
Damn it, Trying to find out why the patch crashes the main Unforgiving Devices mod, Probably a script field that is wrong...

Damn "#(¤! logging that don't even show what's not working.

**Comment by Ethryan** [comment]
It get's stuck on "Installing Unforgiving Devices" in the corner and never advances further than that.

Update: It get's stuck on that with latest NB and no patches loaded.

image

This is a problem...

**Comment by IHateMyKite** [comment]
Hm, interesting. Didn't know the invalid properties can cause such issue. I think it have nothing to do with properties, and issue is just random luck. I will clean the properties and you can then test if it works.

**Comment by Ethryan** [comment]
WARNING: Property UDOM on script udcustomdevicemain attached to UD_CustomDevice_Quest (xx15E73C) cannot be initialized because the script no longer contains that property <- A new one appeared.

If i remove that one, it still won't run, it will still get stuck on "Installing Unforgiving Devices..." and not progress. The log gives no hints, 
unless "Error: Cannot call CloseConfig() on a None object, aborting function call
stack:
	[SKI_ConfigManagerInstance (FE040802)].SKI_ConfigManager.OnMenuClose() - "SKI_ConfigManager.psc" Line 124"

Something wrong with the mcm script?

**Comment by IHateMyKite** [comment]
MCM should have nothing to do with it. But recently we found that there might be incompatibility with OSL arousal. If you have that mod, install in such way that DD still wins the conflict.

EDIT: Also, did you start to get this issue only recently ? What changed ? Did you install some additional mods ? Can you remember which version it was lastly working on and can you test if that version still works ?

**Comment by Ethryan** [comment]
I have tested the [2.1b2](https://github.com/IHateMyKite/UnforgivingDevices/releases/tag/2.1b2) version, and that one works fine, even with all the patches.

I got a lot of NB Builds in my downloads, folder. let me test them 1 at a time and see if something changes.

**Comment by Ethryan** [comment]
image
Note, only the esps required for UD is activated.

**Comment by IHateMyKite** [comment]
Try to disable DCL. I had issues recently with DCL not installing correctly on SE. I had solve it somehow, but I don't remember how

**Comment by IHateMyKite** [comment]
I also see you have OSL arousal installed. Check if it doesn't overwritten DD. So it is loaded like this 
pic

**Comment by Ethryan** [comment]
Testing a version from 6 april that i think worked. It's downloaded after the DAR fixes if i remember correctly. <- Don't work

And OSL is loaded before DD.

- 5 April - Don't work
- NB Below - Don't work
- 4 April - Don't work
- 2 April - Don't work, Testing without DCL - works!
- Testing NB Below without DCL - Don't work

**Comment by IHateMyKite** [comment]
I think it might be related to commit which updated init of the mod.

Try this NB. It is artifact so it have to be extract 2 times. https://github.com/IHateMyKite/UnforgivingDevices/suites/12152819728/artifacts/641132853

**Comment by IHateMyKite** [comment]
Testing NB older then 5 April will have no effect as the beta 2.1b2 was released from NB on this commit https://github.com/IHateMyKite/UnforgivingDevices/commit/33dbd30f88696b4a32cb7b2e4687805314e58b2a. So it doesn't make sense if other NB doesn't work but beta yes

**Comment by IHateMyKite** [comment]
One little detail I forget bout, but some time when you try to open MCM before it is loaded, it can actually break the mod. Did you try to wait first to see if the MCM loaded fully ? Also does MCM of other mods work ?

**Comment by Ethryan** [comment]
MCM for other mods work fine, UD mcm don't work at all and a wait until all text in the top right is gone before i open mcm.

**Comment by IHateMyKite** [comment]
Can you per chance share one of the broken saves ? Best would be for latest NB. I will check scripts variables with Resaver. That will be fastest way to check what is wrong.

**Comment by Ethryan** [comment]
[Save2_D17E0469_0_507269736F6E6572_AbandonedPrison01_000001_20230412173232_1_1.zip](https://github.com/IHateMyKite/UnforgivingDevices_FOMOD/files/11214323/Save2_D17E0469_0_507269736F6E6572_AbandonedPrison01_000001_20230412173232_1_1.zip)

Here, it's one with DCL on. and the NB build from above

**Comment by IHateMyKite** [comment]
Well first thing I see before even going more in is that there is some obvious issue with papyrus not loading correctly because of too much stress
pic
I have encountered same issue numerous times but still didn't found universal way to fix it. I always change randoms thing until it start working. I will try to install latest version of DCL and see if I also get the bug (which is very likely)

**Comment by Ethryan** [comment]
My guess is DCL scripts...

**Comment by Ethryan** [comment]
[Save2_5A8192B7_0_507269736F6E6572_AbandonedPrison01_000001_20230412174553_1_1.zip](https://github.com/IHateMyKite/UnforgivingDevices_FOMOD/files/11214395/Save2_5A8192B7_0_507269736F6E6572_AbandonedPrison01_000001_20230412174553_1_1.zip)
DCL disabled in this one

**Comment by IHateMyKite** [comment]
Hm there is still bunch of active and suspended scripts. Was this save taken immediately after new game or after some time ?

**Comment by Ethryan** [comment]
3 minutes after a new game start. all other mcm menus came online and was working.

**Comment by IHateMyKite** [comment]
Still can't figure out what is wrong. Tested with DCL and it works fine for me. Tried bunch of things, and still didn't manage to break it. Try to run LOOT, maybe you have some mods ordered bad

**Comment by Ethryan** [comment]
Ok, gonna try.

Shutting down other mods and trying to run UD only, to see if it helps.

Question: Do you try with or without: 
<html>
<body>


IWantWidget | No | X
-- | -- | --



</body>
</html>
?
I am trying to run it without.

**Comment by Ethryan** [comment]
[saves.zip](https://github.com/IHateMyKite/UnforgivingDevices_FOMOD/files/11214583/saves.zip)
The Save2_C9D is from the NB
The Save2_D99 is from [2.1b2](https://github.com/IHateMyKite/UnforgivingDevices/releases/tag/2.1b2)

The Save2_D99 works, the C9D don't work... I'm stumped.

**Comment by IHateMyKite** [comment]
I'm now reworking how some modules are initialized, so it should hopefully help.

**Comment by Ethryan** [comment]
Testing NB by installing iWant Widgets - No change at all...

**Comment by IHateMyKite** [comment]
Please, try the latest nb for this PR https://github.com/IHateMyKite/UnforgivingDevices/pull/144. Should be there once build is done https://github.com/IHateMyKite/UnforgivingDevices/actions/runs/4681790896

**Comment by Ethryan** [comment]
Will Do

**Comment by Ethryan** [comment]
This is ready for testing i think.

Only thing is they might be a tad bit hard to get out of. Once they are on the body.

**Comment by IHateMyKite** [comment]
Great work, they work as intended. Only few things to adress

- They have too big gold reward. Should be at max 100 gold IMO
- I assume they are abadon devices. In that case, they should have their name updated so it is clear that it they are abadon device
- There is no way for user to get them in game. There are 2 possible way to fix this. Either just add crafting recipe so user can craft them in game. Alternatively, you can add new abadon suit which will use the piercing. My idea is that you can just copy existing set for yoke/simple set and replace belt/harness with piercing. This is little harder then first option, but I thing will be better for users as they will encounter the piercing on their own. Check this documentation part for more details https://ihatemykite.github.io/Documentation/index.html#File:UD_PatchInit.psc . The default abadon sets are here https://github.com/IHateMyKite/UnforgivingDevices/blob/main/Scripts/Source/UDItemManager.psc
- Might be nice idea to make 8 ring piercing have 8 locks

**Comment by Ethryan** [comment]
Going to keep working on this.

**Comment by Ethryan** [comment]
- [x] They have too big gold reward. Should be at max 100 gold IMO - **Fixed**

- [ ] I assume they are abadon devices. In that case, they should have their name updated so it is clear that it they are abadon device - How about **Lithean** series of devices? Probably gonna add both normal and special versions of this.

- [ ] There is no way for user to get them in game. There are 2 possible way to fix this. Either just add crafting recipe so user can craft them in game. Alternatively, you can add new abadon suit which will use the piercing. My idea is that you can just copy existing set for yoke/simple set and replace belt/harness with piercing. This is little harder then first option, but I thing will be better for users as they will encounter the piercing on their own. Check this documentation part for more details https://ihatemykite.github.io/Documentation/index.html#File:UD_PatchInit.psc . The default abadon sets are here https://github.com/IHateMyKite/UnforgivingDevices/blob/main/Scripts/Source/UDItemManager.psc - **Looking into this**

- [x] Might be nice idea to make 8 ring piercing have 8 locks - **Done**

**Comment by IHateMyKite** [comment]
>     * [ ]  I assume they are abadon devices. In that case, they should have their name updated so it is clear that it they are abadon device - How about **Lithean** series of devices? Probably gonna add both normal and special versions of this.

Adding both version would work best. What are the Lithean you are talking about ?

**Comment by Ethryan** [comment]
Just a made up name, that i am thinking of using instead of Abadon.

**Comment by Ethryan** [comment]
I found **DestroyOnRemove** as a Bool function, 

Does something like **EquipOnRemove** exist or do you need to do some kind of scripting magic for that function?

I would really love to replace 1 item with another when the player lockpicks or unlocks 1 item in this patch.

**Comment by IHateMyKite** [comment]
It currently doesn't exist but it should be not that hard to implement, I would just add new property which you fill with device that will be locked on when current device is unlocked. But I would rather implement this after beta ends.

**Comment by Ethryan** [comment]
Ok, then i will fix this up and make it ready for testing, and keep that functionality in the wip folder for now.

Heads up, you will need the V5 of the original mod to test the patch.

**Comment by IHateMyKite** [comment]
I have tested it, and it looks like that there is no issue. For that reason I'm going for now to merge the PR as I want it to be in nxt beta (mainly the reduced texture sizes). You can continue to work on the changes and merge them later. I want it to be part of next beta.

Also, I think that in future, it might be a good idea to just add new papyrus script for the piercings. It can be named something like "UD_ChastityPiercing_RD". It would extend the vibrator script (as there are variants which use vibrator, as I can see in V5).

**Pull request merged**
