### PR TITLE
Add CACO Patch and Security Overhaul Addon

### LINKED ISSUE #56: (Compatibility) Recipe conflict with CACO
Description: crafting recipes that require salt are conflicting with [Complete Alchemy and Cooking Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/19924) internal recipe mechanics, the mod splits salt piles into smaller items with different id which makes UD recipes unable to be fullfilled. Requires additional patch to be solved.

Version of skyrim: SE
Version of mod: 2.0b11 [72eaa74](https://github.com/IHateMyKite/UnforgivingDevices/commit/72eaa746ea174fb8c34296348770aecfcced5e8e)

### PR DESCRIPTION
**Pull request by Ethryan**
As optional Patches

I can't lock CACO behind an option since it contains & in the modname for the esp. And Fomod Really, Really hates that.

Security Overhaul Don't have an esp to limit it with so they are unlocked for now regardless what mods are in the loadorder.
The ESP for this is necessary to differentiate the lock used from the Noble Chest, it redirects to a different copy of the Noble chest nif. but the ini file is what redirects and shows a new lock instead of the stock standard.
su
And this pic is from me testing it ingame with a Belt.

The Lock looks nice ingame, don't know why it is white when i took a printscreen.

### CODE REVIEW

**Comment by Ethryan** [comment]
Now it works.

**Comment by IHateMyKite** [comment]
Hi, nice work. Only 2 small things

If its possible, the lock texture should smaller. It took me a while to realize that it is supposed to be lock. All locks in DD are very small so proportion of the lock mechanism and lock body is much bigger. 

This is the size of lock from straitjacket texture. I have only drawn the virtual cylinder, so it can be better compared
pic

Lastly, the SU folder have 16 MB, so it should be better to move everything that is not esp to different folder, which will be shared to both esp and esl option. This way it will decrease the size of whole fomod. Right now both SU and SUESL have the textures and meshes, which should be not case.

**Comment by Ethryan** [comment]
It's hard for me to edit the nif and make it smaller since i'm not a modeler or texturer, the files are from [Here](https://www.nexusmods.com/skyrimspecialedition/mods/59961/?tab=description) with a few edits to change texture paths.
I will try and see if i can zoom the lock out some so it looks smaller, but i don't know if it's possible.

image

**Comment by IHateMyKite** [comment]
I'm tring to edit the mesh with bodyslide and so far it looks promising. Only issue is that the mesh sucks ass. For some reason the vertices are all over the place. Because of that I cant make the key hole bigger
pic
I will try to update the texture next to give it a less rusty feel and then see how it looks ingame

**Comment by IHateMyKite** [comment]
also, the esp patch is present in SUother. Is this intentional ? As now there are 3 different patches

**Comment by Ethryan** [comment]
Im working on a padlock for this insted
image

Going to test it now

**Comment by Ethryan** [comment]
image

Thoughts?

**Comment by IHateMyKite** [comment]
Looks great, but imho it looks like the lock is too big big. Because the proportion of the knife and lock is too big. I thing it will look much better if the whole lock would be little smaller.
I just also finished.
ScreenShot_Astrix2199
I think that it might not be bad idea to add both and then add some switch on main repo. There would only need to be added another container which will use another lock.

**Comment by Ethryan** [comment]
Making a switch is really easy, i just have to change 1 file. and then the fomod

**Comment by Ethryan** [comment]
Need the new nif for the shacklelock

**Comment by IHateMyKite** [comment]
I added the shackle lock and updated, so it can be better selected. Also compressed new images so the whole installer is smaller

**Comment by Ethryan** [comment]
I think this is done then.

**Comment by IHateMyKite** [comment]
Great work

**Pull request merged**
